server:
    context-path: /guower
    port: 8981
    tomcat:
        max-threads: 1000
        min-spare-threads: 30
spring:
  profiles:
  # dev|prod|test
      active: dev
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  jmx:
      enabled: false
  jpa:
      show-sql: true
  #mybatis使用spring-druid数据源连接池配置log4j打印sql语句以及开启监控平台 https://segmentfault.com/a/1190000005642328
  datasource:
#  一般情况，请不要使用root账号
#   username: guoweruser
#   password: guower|.__^^^
    username: guower
    password: guowerdb123Xx_..
    type: com.alibaba.druid.pool.DruidDataSource
    dbType: mysql
    #mysql:select 1; oracle:SELECT 1 FROM DUAL
    validationQuery: SELECT 1
    driverClassName: com.mysql.jdbc.Driver
    maxActive: 200
    maxWait: 60000
    minIdle: 5
    initialSize: 5
    maxPoolPreparedStatementPerConnectionSize: 20
    minEvictableIdleTimeMillis: 300000
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    filters: stat,wall,log4j
    poolPreparedStatements: true
    testOnBorrow: true
    testOnReturn: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    #超时回收会影响性能，正式环境最好关闭
    remove-abandoned: true #是否自动回收超时连接
    remove-abandoned-timeout: 73 #超时时间(以秒数为单位)
    log-abandoned: true #是否在自动回收超时连接的时候打印连接的超时错误
#    redis配置
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 47.100.34.60  # Redis服务器地址
    password: nozuonodie # Redis服务器连接密码（默认为空）
    pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
    port: 6379
    timeout: 0
  session:
        store-type: redis
  thymeleaf:
    cache: false
  devtools:  ## 这个节点可以不要，默认就是这样
    restart:
      enabled: true #热部署生效,默认也是true
      exclude: WEB-INF/** #spring.devtools.restart.additional-paths: src/main/java  #classpath目录下的WEB-INF文件夹内容修改不重启
  http:
    multipart:
      max-file-size: 500MB #文件最大
      max-request-size: 5000MB
    encoding:
      charset: utf-8
      force: true
      enabled: true
      #设置总上传数据总大小
  ### http://114.215.84.189:15672/
  ## springboot集成RabbitMQ http://www.cnblogs.com/ityouknow/p/6120544.html
  ### 注意，网页访问使用的端口是15672；程序使用的是5672
#  rabbitmq:
#    host: 39.104.116.24
#    port: 5672
#    username: rootuser
#    password: 123456
    ##国际化 i18n
    ##指定message的basename，多个以逗号分隔，如果不加包名的话，默认从classpath路径开始，默认: messages； 注意这个必须要有messages.properties文件，否则别的文件也不会加载
  messages:
    basename: i18n/messages
    cache-seconds: 60 #默认是-1，属性文件永不过期，这里是60s,60s之后重新加载该文件。
#fastdfs 配置
fdfs:
    connectTimeout: 600
    soTimeout: 1500
    thumbImage:
        height: 150
        width: 150
    trackerNginxAddr: 47.100.34.60:8000
    trackerList:
    - 47.100.34.60:22122
#日志
logging:
    config: classpath:logback-spring.xml
    #linux 位置 /tomcat/bin/logs/
    file: ./logs/guower/guower_business.log
#    level:
#      root: INFO  #debug  #TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
#      org.springframework: INFO
#      org.apache: error
#      com.ourslook.guower.BusinessApplication: INFO
#      # Druid
#      com.alibaba.druid: debug
#      org.apache.catalina: debug
#      Ourslook*20180520
#本系统业务配置
ourslook:
    redis-session-enable: false
    security-acess: false
    fastdfs-enable: false
    tomcat-virtal-path: true
    open-short-msg: true
    casServerUrlPrefix: http://10.10.9.9:83/cas
    casclientUrlPrefix: http://10.10.9.9:83/safety
    casLoginUrl: "${ourslook.casServerUrlPrefix}/login"
    casLogoutUrl: "${ourslook.casServerUrlPrefix}/logout?service=${ourslook.casclientUrlPrefix}"
    casclientCasFilterUrlPattern: /shiro-cas
    casclientCasService: "${ourslook.casclientUrlPrefix}${ourslook.casclientCasFilterUrlPattern}"
    casclientLoginUrl: "${ourslook.casLoginUrl}?service=${ourslook.casclientUrlPrefix}/shiro-cas"